from __future__ import annotations

from pathlib import Path

import numpy as np
from numpy.typing import NDArray
from pydantic import BaseModel, ConfigDict

from synth.models.vital_control_name import VitalControlName
from synth.models.vital_preset_model import VitalPreset


CONTROL_NAMES = tuple(VitalControlName)
CONTROL_INDEX = {name: index for index, name in enumerate(CONTROL_NAMES)}


class ControlStatistics(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    mean: tuple[float, ...]
    standard_deviation: tuple[float, ...]
    minimum: tuple[float, ...]
    maximum: tuple[float, ...]

    @classmethod
    def fit(cls, presets: tuple[VitalPreset, ...]) -> ControlStatistics:
        values: list[list[float]] = [[] for _ in CONTROL_NAMES]
        for preset in presets:
            for name, value in preset.settings.controls.items():
                values[CONTROL_INDEX[name]].append(value)
        means = tuple(float(np.mean(item)) if item else 0.0 for item in values)
        deviations = tuple(
            max(float(np.std(item)), 1e-6) if item else 1.0 for item in values
        )
        minima = tuple(float(np.min(item)) if item else 0.0 for item in values)
        maxima = tuple(float(np.max(item)) if item else 0.0 for item in values)
        return cls(
            mean=means,
            standard_deviation=deviations,
            minimum=minima,
            maximum=maxima,
        )

    def encode(self, preset: VitalPreset) -> tuple[NDArray[np.float32], NDArray[np.bool_]]:
        vector = np.zeros(len(CONTROL_NAMES), dtype=np.float32)
        mask = np.zeros(len(CONTROL_NAMES), dtype=np.bool_)
        for name, value in preset.settings.controls.items():
            index = CONTROL_INDEX[name]
            vector[index] = (value - self.mean[index]) / self.standard_deviation[index]
            mask[index] = True
        return vector, mask

    def apply(
        self,
        template: VitalPreset,
        normalized_controls: NDArray[np.float32],
    ) -> VitalPreset:
        if normalized_controls.shape != (len(CONTROL_NAMES),):
            raise ValueError(f"Unexpected control vector shape {normalized_controls.shape}")
        controls: dict[VitalControlName, float] = {}
        for name in template.settings.controls:
            index = CONTROL_INDEX[name]
            decoded = float(
                normalized_controls[index] * self.standard_deviation[index]
                + self.mean[index]
            )
            controls[name] = float(np.clip(decoded, self.minimum[index], self.maximum[index]))
        settings = template.settings.model_copy(update={"controls": controls})
        return template.model_copy(
            update={
                "preset_name": "Generated by vital_transformer_v1",
                "author": "synth",
                "comments": "Sound-driven reconstruction",
                "settings": settings,
            }
        )


def load_presets(dataset: Path, rows: tuple[dict[str, object], ...]) -> tuple[VitalPreset, ...]:
    return tuple(VitalPreset.from_file(dataset / str(row["preset_file"])) for row in rows)
